### ISSUE TITLE
setup.py does not specify dependencies suitable for pip / easy_install 

### ISSUE THREAD

**Issue by jjguy** [jjguy/heatmap#11]
Running easy_install heatmap should also install PIL / Pillow if it's not already on the system.  As currently written, it's not.

```
[root@localhost pip-1.2.1]# easy_install heatmap
Searching for heatmap
Reading http://pypi.python.org/simple/heatmap/
Reading http://jjguy.com/heatmap/
Best match: heatmap 2.2.1
Downloading http://jjguy.com/heatmap/heatmap-2.2.1.zip
Processing heatmap-2.2.1.zip
Running heatmap-2.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-NqLtUD/heatmap-2.2.1/egg-dist-tmp-RMyYR1
zip_safe flag not set; analyzing archive contents...
Adding heatmap 2.2.1 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/heatmap-2.2.1-py2.6-linux-x86_64.egg
Processing dependencies for heatmap
Finished processing dependencies for heatmap
[root@localhost pip-1.2.1]# python
Python 2.6.6 (r266:84292, Sep 11 2012, 08:34:23) 
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import heatmap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/heatmap-2.2.1-py2.6-linux-x86_64.egg/heatmap/__init__.py", line 6, in <module>
    from heatmap import Heatmap
  File "/usr/lib/python2.6/site-packages/heatmap-2.2.1-py2.6-linux-x86_64.egg/heatmap/heatmap.py", line 9, in <module>
    from PIL import Image
ImportError: No module named PIL
>>> 
```

**Comment by kwauchope** [comment]
This is fixed in my projection branch fixingcrs that I haven't put a pull request in for until I've used it a little more in anger. Combination of fixing #12 and adding install_requires = ['Pillow']
